### NumPy HOME

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### NumPy Getting Started

In [3]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
print(np.__version__)

2.2.5


### NumPy Creating Arrays

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np

arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np

arr = np.array(42)
print(arr)

42


In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [1]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

arr = np.array(
    [
        [[1, 2, 3], [4, 5, 6]],
        [
            [
                1,
                2,
                3,
            ],
            [4, 5, 6],
        ],
    ]
)
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [1]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [2]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### NumPy Array Indexing

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


In [4]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])

2


In [6]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


In [9]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


In [1]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1,4])

5th element on 2nd row:  10


In [ ]:
import numpy as np
arr = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [5]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1,-1])

Last element from 2nd dim:  10


### NumPy Array Slicing

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:4])

[1 2 3 4]


In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])

[5 6]


In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])

[1 3 5 7]


In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [4]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


In [5]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### NumPy Array Slicing

In [1]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr.dtype)

int64


In [2]:
import numpy as np

arr = np.array(["array", "banana", "cherry"])

print(arr.dtype)

<U6


In [4]:
import numpy as np

arr = np.array([1,2,3,4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [6]:
import numpy as np

arr = np.array([1,2,3,4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [7]:
import numpy as np

arr = np.array(["a", "2", "3"], dtype="i")

ValueError: invalid literal for int() with base 10: 'a'

In [8]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [1]:
import numpy as np
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [2]:
import numpy as np

arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### NumPy Copy vs View

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### Numpy Array Shape

In [2]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


In [3]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('shape of array: ', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array:  (1, 1, 1, 1, 4)


### NumPy Array Reshape

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(3,3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### NumPy Array Iterating

In [1]:
import numpy as np

arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [4]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print("x represents the 2-D array:")
  print(x)

x represents the 2-D array:
[[1 2 3]
 [4 5 6]]
x represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


In [7]:
import numpy as np

arr = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [2]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [3]:
import numpy as np

arr = np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [5]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7
